[package]
name = "nh3"
version = "0.2.15"
authors = ["messense <messense@icloud.com>"]
edition = "2018"
description = "Python bindings to the ammonia HTML sanitization library."
license = "MIT"
repository = "https://github.com/messense/nh3"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
ammonia = "4.0.0"
pyo3 = { version = "0.20.3", features = ["abi3-py37", "extension-module"] }
